version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python app/manage.py runserver 0:8000
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: "on-failure"

volumes:
  postgres_data:
