# Generated by Django 4.2.3 on 2023-07-10 10:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_add_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "classes",
                    models.ManyToManyField(
                        related_name="students", to="schedule.class"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
